"""
Inbound SMS handler for Africa's Talking webhook.
Handles STOP commands, scheduling replies, and intent classification.
"""
from __future__ import annotations
import json
from datetime import datetime
from ..llm import chat_json

STOP_KEYWORDS = {"stop", "unsubscribe", "cancel", "quit", "end", "remove"}
YES_KEYWORDS = {"yes", "y", "ok", "sure", "works", "confirmed", "confirm", "yep", "yeah"}
NO_KEYWORDS = {"no", "n", "nope", "not available", "busy", "can't", "cannot"}


def classify_sms_reply(message: str, context: str = "") -> dict:
    """
    Classify an inbound SMS reply.
    Returns intent, suggested action, and brief response.
    """
    msg_lower = message.lower().strip()

    # Immediate STOP handling (no LLM required — must be instant)
    if any(kw in msg_lower for kw in STOP_KEYWORDS):
        return {
            "intent": "UNSUBSCRIBE",
            "confidence": "high",
            "action": "unsubscribe_immediately",
            "response": None,  # No reply after STOP
            "logged_at": datetime.utcnow().isoformat(),
        }

    # Simple yes/no for scheduling
    if any(kw in msg_lower for kw in YES_KEYWORDS) and len(message) < 30:
        return {
            "intent": "SCHEDULING_CONFIRM",
            "confidence": "high",
            "action": "book_call",
            "response": None,  # Will be generated by scheduler
            "logged_at": datetime.utcnow().isoformat(),
        }

    if any(kw in msg_lower for kw in NO_KEYWORDS) and len(message) < 30:
        return {
            "intent": "SCHEDULING_DECLINE",
            "confidence": "high",
            "action": "propose_alternative_time",
            "response": None,
            "logged_at": datetime.utcnow().isoformat(),
        }

    # Complex replies → LLM classification
    return _classify_with_llm(message, context)


def _classify_with_llm(message: str, context: str = "") -> dict:
    """Use LLM via OpenRouter to classify complex SMS replies."""
    prompt = f"""Classify this SMS reply from a business prospect.

Context: {context or 'Scheduling follow-up after email outreach from Tenacious Consulting'}

SMS: {message}

Return JSON with:
- intent: SCHEDULING_CONFIRM | SCHEDULING_DECLINE | ALTERNATIVE_TIME | QUESTION | UNSUBSCRIBE | POSITIVE | NEGATIVE | UNCLEAR
- confidence: high/medium/low
- action: book_call | propose_alternative_time | route_to_human | unsubscribe_immediately | answer_question | close_thread
- response: brief reply draft (max 140 chars, in Tenacious voice, or null)
- notes: one-line note for CRM
"""
    try:
        raw = chat_json(user_prompt=prompt, max_tokens=256)
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.rsplit("```", 1)[0]
        result = json.loads(raw)
    except Exception:
        result = {
            "intent": "UNCLEAR",
            "confidence": "low",
            "action": "route_to_human",
            "response": None,
            "notes": "Could not classify SMS reply — needs human review.",
        }

    result["logged_at"] = datetime.utcnow().isoformat()
    return result


def parse_at_webhook(payload: dict) -> dict:
    """Parse Africa's Talking inbound SMS webhook."""
    return {
        "from": payload.get("from"),
        "to": payload.get("to"),
        "text": payload.get("text", "").strip(),
        "message_id": payload.get("id"),
        "date": payload.get("date"),
        "link_id": payload.get("linkId"),
    }
